# Generated by Django 4.2 on 2026-01-21 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Staff', '0004_alter_employeesalary_base_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('fulltime', 'Toàn thời gian'), ('parttime', 'Bán thời gian'), ('trainee', 'Thực tập sinh')], max_length=20, unique=True, verbose_name='Loại nhân viên')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lương theo giờ (₫)')),
                ('shift_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lương theo ca (₫)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lương cơ bản',
                'verbose_name_plural': 'Lương cơ bản',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Tháng')),
                ('year', models.IntegerField(verbose_name='Năm')),
                ('total_shifts', models.IntegerField(default=0, verbose_name='Tổng số ca')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Tổng giờ làm')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lương cơ bản (₫)')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Thưởng (₫)')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Khấu trừ (₫)')),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng lương (₫)')),
                ('status', models.CharField(choices=[('calculated', 'Đã tính'), ('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy')], default='calculated', max_length=20, verbose_name='Trạng thái')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Bảng lương',
                'verbose_name_plural': 'Bảng lương',
                'ordering': ['-year', '-month', 'employee'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.RemoveField(
            model_name='salarypayment',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='salarypayment',
            name='salary',
        ),
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
        migrations.DeleteModel(
            name='SalaryConfig',
        ),
        migrations.DeleteModel(
            name='SalaryPayment',
        ),
    ]
