# Generated by Django 4.2.28 on 2026-02-09 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lương theo giờ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Chủ quán'), ('staff', 'Nhân viên'), ('customer', 'Khách hàng')], default='customer', max_length=10, verbose_name='Vai trò'),
        ),
    ]
