# Generated by Django 4.2.28 on 2026-02-04 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shifts', '0003_alter_shiftregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftregistration',
            options={'ordering': ['-registered_at']},
        ),
        migrations.AddField(
            model_name='shiftregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('assigned', 'Đã phân công'), ('rejected', 'Từ chối')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đăng ký'),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shifts.shift'),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
