# Generated by Django 4.2.28 on 2026-02-04 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shifts', '0004_alter_shiftregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftregistration',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Shifts.shift'),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='status',
            field=models.CharField(choices=[('registered', 'Đã đăng ký'), ('assigned', 'Đã phân công'), ('cancelled', 'Đã hủy')], default='registered', max_length=20),
        ),
    ]
