# Generated by Django 4.2.28 on 2026-02-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cancel_reason_order_canceled_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tổng tiền của đơn hàng (tự động tính)', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at', 'status'], name='orders_orde_created_4a9c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'total_amount'], name='orders_orde_status_3bc4de_idx'),
        ),
    ]
