# Generated by Django 4.2.28 on 2026-02-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bill_created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_billed',
        ),
    ]
