# Generated by Django 4.2.28 on 2026-02-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_options_remove_order_bill_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số tiền giảm giá (VNĐ)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ'), ('transfer', 'Chuyển khoản'), ('momo', 'Momo'), ('zalopay', 'ZaloPay')], default='cash', max_length=10),
        ),
    ]
